#    container_name: moltega
services:
  bot:
    build: .
    restart: unless-stopped
    command: sh -c "npm run deploycommands && npm run start"
    env_file:
      - .env.prod
    volumes:
      - ./data:/app/data
    profiles: ["prod"]

  bot-dev:
    build: .
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    # working_dir: /app
    command: sh -c "npm run deploycommands && npm run start:dev"
    env_file:
      - .env
    profiles: ["dev"]
